config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: "home#index"

  devise_for :users, controllers: {
    sessions: 'user/sessions'
  } do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :questions, except: [:edit] do
    resources :answers, only: [:create, :update, :destroy], shallow: true do
      member do
        post :mark_as_best
      end
    end
    resource :subscription, only: %i[create destroy]
  end

  resources :files, only: [:destroy]
  resources :links, only: :destroy
  resources :rewards, only: :index

  concern :voteable do |options|
    member do
      resources :votes, { only: [:create] }.merge(options)
    end
  end

  resources :questions, only: [], param: :voteable_id do
    concerns :voteable, defaults: { voteable_type: 'question' }, as: :question_votes
  end

  resources :answers, only: [], param: :voteable_id do
    concerns :voteable, defaults: { voteable_type: 'answer' }, as: :answer_votes
  end

  resources :votes, only: [:destroy]

  concern :commentable do |options|
    member do
      resources :comments, { only: [:create] }.merge(options)
    end
  end

  resources :questions, only: [], param: :commentable_id do
    concerns :commentable, defaults: { commentable_type: 'question' }, as: :question_comments
  end

  resources :answers, only: [], param: :commentable_id do
    concerns :commentable, defaults: { commentable_type: 'answer' }, as: :answer_comments
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: [:new, :edit] do
        resources :answers, except: [:new, :edit], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Linkable
  include Voteable
  include Commentable

  belongs_to :user
  belongs_to :question

  has_many_attached :files

  after_create :send_notification

  validates :body, presence: true

  def mark_as_best
    Answer.transaction do
      question.answers.update_all(best: false)
      question.reward&.update!(user_id: user_id)
      update!(best: true)
    end
  end

  def send_notification
    NotificationService.new.new_answer(self)
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_question, only: %i[create index]
  before_action :find_answer, only: %i[update destroy mark_as_best]

  authorize_resource

  def index
    @answers = @question.answers
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user

    if @answer.save
      @notice = 'The answer has been successfully created'
    else
      @alert = 'The answer has not been created'
    end
    publish_answer
  end

  def update
    @notice = 'The answer has been successfully updated' if @answer.update(answer_params)
  end

  def destroy
    @answer.destroy
    @notice = 'The answer has been successfully deleted'
  end

  def mark_as_best
    @answer.mark_as_best
  end

  private

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[name url _destroy])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def publish_answer
    return if @answer.errors.present?

    ActionCable.server.broadcast(
      "questions/#{@answer.question_id}/answers",
      {
        id: @answer.id,
        author_id: @answer.user_id,
        templates: {
          answer: render_template(
            partial: 'websockets/answers/answer',
            locals: { answer: @answer }
          ),
          vote_links: render_template(
            partial: 'websockets/shared/votes/vote_links',
            locals: { voteable: @answer, vote: @answer.votes.new }
          )
        }
      }
    )
  end
end

app/controllers/api/v1/answers_controller.rb
module Api
  module V1
    class AnswersController < BaseController
      before_action :find_question, only: [:index, :create]
      before_action :find_answer, only: [:show, :update, :destroy]

      load_and_authorize_resource

      def index
        render json: @question.answers
      end

      def show
        render json: @answer, serializer: SingleAnswerSerializer
      end

      def create
        @answer = @question.answers.new(answer_params)
        @answer.user = current_resource_owner

        if @answer.save
          render json: @answer
        else
          render json: { errors: @answer.errors.full_messages }, status: :unprocessable_entity
        end
      end

      def update
        if @answer.update(answer_params)
          render json: @answer, serializer: SingleAnswerSerializer
        else
          render json: { errors: @answer.errors.full_messages }, status: :unprocessable_entity
        end
      end

      def destroy
        @answer.destroy
        render json: { success: true }
      end

      private

      def answer_params
        params.require(:answer).permit(:body)
      end

      def find_question
        @question = Question.find(params[:question_id])
      end

      def find_answer
        @answer = Answer.with_attached_files.find(params[:id])
      end
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  .answer id='answer-id-#{answer.id}' class=('best' if answer.best)
    p = answer.body

    = render "/votes/vote_block", vote: (current_user&.vote_by(answer) || answer.votes.new), voteable: answer
     = render "/votes/vote_rating", vote: @vote, voteable: answer

    - if answer.files.attached?
      - answer.files.each do |file|
        = render '/files/file', file: file

    - if answer&.links.present?
      = render 'links/index', resource: answer

    - if user_signed_in?
      - if can?(:mark_as_best, answer)
        p.mark-as-best = link_to 'Mark as best', mark_as_best_answer_path(answer), method: :post, remote: true

      - if can?(:update, answer)
        p = link_to 'Edit answer', '#', class: 'edit-answer-link', data: { answer_id: answer.id }

        .edit-answer-form
          .answer-errors
          = render 'answers/edit_form', answer: answer
      - if can?(:destroy, answer)
        p = link_to 'Delete answer', answer_path(answer), method: :delete, remote: true

      p New comment
      .new-comment-form
        .comment-errors
        = render '/comments/form', commentable: answer

    p Comments
    .answer-comments
      = render answer.comments.order(created_at: :asc)

app/views/answers/_edit_form.html.slim
= form_with model: answer, class: 'hidden', html: { id: "edit-answer-form-#{answer.id}" }, local: false do |f|
  p
    = f.label :body
    = f.text_field :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  p Links:
  .answer-links
    = f.fields_for :links do |link|
      = render 'links/link_fields', f: link
    p.links
      = link_to_add_association 'add link', f, :links, partial: 'links/link_fields'
  p
    = f.submit 'Save'

app/views/answers/_form.html.slim
= form_with model: [@question, @answer], local: false do |f|
  p
    = f.label :body
    = f.text_field :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  p Links:
  .answer-links
    = f.fields_for :links do |link|
      = render 'links/link_fields', f: link
    p.links
      = link_to_add_association 'add link', f, :links, partial: 'links/link_fields'
  p
    = f.submit 'Answer'

app/views/answers/create.js.erb
<% if @answer.links.any?(&:gist?) %>
window.location.reload(false); // fix partial view of answer script
<% else %>
  $(".new-answer-form .answer-errors").html("<%= render 'shared/errors', resource: @answer %>");

  <% if @answer.persisted? %>
    $(".answers").append("<%= j render @answer %>");
    $(".new-answer-form #answer_body").val("");
    $(".new-answer-form #answer_files").val("");
    $(".new-answer-form #answer_files").prop("disabled", false);
    $(".new-answer-form .direct-upload").remove();
    $(".new-answer-form .nested-fields").remove();
    onAjaxCommentForm($("<%= "#answer-id-#{@answer.id} .new-comment-form form" %>"));
  <% end %>
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.destroyed? %>
$(".answers #answer-id-<%= @answer.id %>").remove();
<% end %>

app/views/answers/mark_as_best.js.erb
$('.answers').html('<%= j render @answer.question.answers %>');
$(".answers .best .mark-as-best").removeClass("hidden");
$(".answers .best").removeClass("best");
$(".answers #answer-id-<%= @answer.id %>").addClass("best");

app/views/answers/update.js.erb
<% if @answer.links.any?(&:gist?) %>
window.location.reload(false);
<% else %>
$("#answer-id-<%= @answer.id %> .edit-answer-form .answer-errors").html("<%= render 'shared/errors', resource: @answer %>");

<% if @answer.errors.empty? %>
$("#answer-id-<%= @answer.id %>").replaceWith("<%= j render @answer, best: @answer.best %>");
<% end %>
<% end %>