config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: "home#index"

  devise_for :users, controllers: {
    sessions: 'user/sessions'
  } do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :questions, except: [:edit] do
    resources :answers, only: [:create, :update, :destroy], shallow: true do
      member do
        post :mark_as_best
      end
    end
    resource :subscription, only: %i[create destroy]
  end

  resources :files, only: [:destroy]
  resources :links, only: :destroy
  resources :rewards, only: :index

  concern :voteable do |options|
    member do
      resources :votes, { only: [:create] }.merge(options)
    end
  end

  resources :questions, only: [], param: :voteable_id do
    concerns :voteable, defaults: { voteable_type: 'question' }, as: :question_votes
  end

  resources :answers, only: [], param: :voteable_id do
    concerns :voteable, defaults: { voteable_type: 'answer' }, as: :answer_votes
  end

  resources :votes, only: [:destroy]

  concern :commentable do |options|
    member do
      resources :comments, { only: [:create] }.merge(options)
    end
  end

  resources :questions, only: [], param: :commentable_id do
    concerns :commentable, defaults: { commentable_type: 'question' }, as: :question_comments
  end

  resources :answers, only: [], param: :commentable_id do
    concerns :commentable, defaults: { commentable_type: 'answer' }, as: :answer_comments
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: [:new, :edit] do
        resources :answers, except: [:new, :edit], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :user, uniqueness: { scope: :question_id }
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  authorize_resource

  def create
    @subscription = current_user.subscriptions.find_or_create_by(question: question)
  end

  def destroy
    @subscription = current_user.subscriptions.find_by(question: question)
    @subscription&.destroy
  end

  private

  def question
    @question ||= Question.find(params[:question_id])
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_subscription.html.slim
.subscription
  - if current_user.subscribed?(question)
    | You are subscribed to this question
    = link_to 'Unsubscribe', question_subscription_path(question_id: question.id), method: :delete, remote: true
  - else
    = link_to 'Subscribe', question_subscription_path(question_id: question.id), method: :post, remote: true

app/views/subscriptions/create.js.erb
<% if @subscription.persisted? %>
$(".subscription").html('You are subscribed to this question')
$(".subscription").append('<%= link_to "Unsubscribe", question_subscription_path(question_id: @subscription.question_id), method: :delete, remote: true %>')
<% end %>

app/views/subscriptions/destroy.js.erb
<% unless @subscription.persisted? %>
$(".subscription").html('<%= link_to "Subscribe", question_subscription_path(question_id: @subscription.question_id), method: :post, remote: true %>')
<% end %>